#pragma once

#ifdef _MSC_VER
	#pragma pack(push, 0x01)
#endif

namespace SDK
{
//---------------------------------------------------------------------------------------------------------------------
// CLASSES
//---------------------------------------------------------------------------------------------------------------------

// 0x59B8 (0x60E8 - 0x730)
// AnimBlueprintGeneratedClass GrindRail_Player_LayerAnimBP.GrindRail_Player_LayerAnimBP_C
class UGrindRail_Player_LayerAnimBP_C : public UFortGrindRailLayerAnimInstance
{
public:
	struct FPointerToUberGraphFrame              UberGraphFrame;                                    // 0x730(0x8)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimBlueprintGeneratedMutableData    __AnimBlueprintMutables;                           // 0x738(0x58)(HasGetValueTypeHash)
	struct FAnimSubsystemInstance                AnimBlueprintExtension_PropertyAccess;             // 0x790(0x8)()
	struct FAnimSubsystemInstance                AnimBlueprintExtension_Base;                       // 0x798(0x8)()
	struct FAnimNode_Root                        AnimGraphNode_Root_7;                              // 0x7A0(0x20)()
	struct FAnimNode_LinkedInputPose             AnimGraphNode_LinkedInputPose_8;                   // 0x7C0(0xC0)()
	struct FAnimNode_LinkedInputPose             AnimGraphNode_LinkedInputPose_7;                   // 0x880(0xC0)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_81;                 // 0x940(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_80;                 // 0x968(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_79;                 // 0x990(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_78;                 // 0x9B8(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_77;                 // 0x9E0(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_76;                 // 0xA08(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_75;                 // 0xA30(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_74;                 // 0xA58(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_73;                 // 0xA80(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_72;                 // 0xAA8(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_71;                 // 0xAD0(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_70;                 // 0xAF8(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_69;                 // 0xB20(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_68;                 // 0xB48(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_67;                 // 0xB70(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_66;                 // 0xB98(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_65;                 // 0xBC0(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_64;                 // 0xBE8(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_63;                 // 0xC10(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_62;                 // 0xC38(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_61;                 // 0xC60(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_60;                 // 0xC88(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_59;                 // 0xCB0(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_58;                 // 0xCD8(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_57;                 // 0xD00(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_56;                 // 0xD28(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_55;                 // 0xD50(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_54;                 // 0xD78(0x28)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_32;                   // 0xDA0(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_41;                      // 0xDE8(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_31;                   // 0xE08(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_40;                      // 0xE50(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_30;                   // 0xE70(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_39;                      // 0xEB8(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_29;                   // 0xED8(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_38;                      // 0xF20(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_28;                   // 0xF40(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_37;                      // 0xF88(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_27;                   // 0xFA8(0x48)()
	struct FAnimNode_RotateRootBone              AnimGraphNode_RotateRootBone_6;                    // 0xFF0(0xB0)()
	struct FAnimNode_RotateRootBone              AnimGraphNode_RotateRootBone_5;                    // 0x10A0(0xB0)()
	struct FAnimNode_RotationOffsetBlendSpace    AnimGraphNode_RotationOffsetBlendSpace_5;          // 0x1150(0x118)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_36;                      // 0x1268(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_26;                   // 0x1288(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_35;                      // 0x12D0(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_25;                   // 0x12F0(0x48)()
	struct FAnimNode_RotateRootBone              AnimGraphNode_RotateRootBone_4;                    // 0x1338(0xB0)()
	struct FAnimNode_RotateRootBone              AnimGraphNode_RotateRootBone_3;                    // 0x13E8(0xB0)()
	struct FAnimNode_RotationOffsetBlendSpace    AnimGraphNode_RotationOffsetBlendSpace_4;          // 0x1498(0x118)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_34;                      // 0x15B0(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_24;                   // 0x15D0(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_33;                      // 0x1618(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_23;                   // 0x1638(0x48)()
	struct FAnimNode_RotateRootBone              AnimGraphNode_RotateRootBone_2;                    // 0x1680(0xB0)()
	struct FAnimNode_RotateRootBone              AnimGraphNode_RotateRootBone_1;                    // 0x1730(0xB0)()
	struct FAnimNode_RotationOffsetBlendSpace    AnimGraphNode_RotationOffsetBlendSpace_3;          // 0x17E0(0x118)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_32;                      // 0x18F8(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_22;                   // 0x1918(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_31;                      // 0x1960(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_21;                   // 0x1980(0x48)()
	struct FAnimNode_RotationOffsetBlendSpace    AnimGraphNode_RotationOffsetBlendSpace_2;          // 0x19C8(0x118)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_30;                      // 0x1AE0(0x20)()
	struct FAnimNode_StateMachine                AnimGraphNode_StateMachine_10;                     // 0x1B00(0xC8)()
	struct FAnimNode_RotateRootBone              AnimGraphNode_RotateRootBone;                      // 0x1BC8(0xB0)()
	struct FAnimNode_BlendListByBool             AnimGraphNode_BlendListByBool_1;                   // 0x1C78(0x48)()
	struct FAnimNode_Root                        AnimGraphNode_Root_6;                              // 0x1CC0(0x20)()
	struct FAnimNode_LinkedInputPose             AnimGraphNode_LinkedInputPose_6;                   // 0x1CE0(0xC0)()
	struct FAnimNode_Root                        AnimGraphNode_Root_5;                              // 0x1DA0(0x20)()
	struct FAnimNode_LinkedInputPose             AnimGraphNode_LinkedInputPose_5;                   // 0x1DC0(0xC0)()
	struct FAnimNode_Root                        AnimGraphNode_Root_4;                              // 0x1E80(0x20)()
	struct FAnimNode_LinkedInputPose             AnimGraphNode_LinkedInputPose_4;                   // 0x1EA0(0xC0)()
	struct FAnimNode_SaveCachedPose              AnimGraphNode_SaveCachedPose_4;                    // 0x1F60(0x100)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_53;                 // 0x2060(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_52;                 // 0x2088(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_51;                 // 0x20B0(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_50;                 // 0x20D8(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_49;                 // 0x2100(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_48;                 // 0x2128(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_47;                 // 0x2150(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_46;                 // 0x2178(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_45;                 // 0x21A0(0x28)()
	struct FAnimNode_UseCachedPose               AnimGraphNode_UseCachedPose_11;                    // 0x21C8(0x28)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive_14;                    // 0x21F0(0xC8)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_20;                   // 0x22B8(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_29;                      // 0x2300(0x20)()
	struct FAnimNode_ApplyMeshSpaceAdditive      AnimGraphNode_ApplyMeshSpaceAdditive;              // 0x2320(0xD0)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_19;                   // 0x23F0(0x48)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_18;                   // 0x2438(0x48)()
	struct FAnimNode_BlendListByBool             AnimGraphNode_BlendListByBool;                     // 0x2480(0x48)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_2;             // 0x24C8(0x20)()
	struct FAnimNode_RefPose                     AnimGraphNode_LocalRefPose;                        // 0x24E8(0x10)()
	struct FAnimNode_LayeredBoneBlend            AnimGraphNode_LayeredBoneBlend;                    // 0x24F8(0xE0)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive_13;                    // 0x25D8(0xC8)()
	struct FAnimNode_BlendSpacePlayer            AnimGraphNode_BlendSpacePlayer_7;                  // 0x26A0(0x70)()
	struct FAnimNode_ModifyBone                  AnimGraphNode_ModifyBone;                          // 0x2710(0x128)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_2;             // 0x2838(0x20)()
	struct FAnimNode_ResetRoot                   AnimGraphNode_ResetRoot;                           // 0x2858(0xD8)()
	struct FAnimNode_UseCachedPose               AnimGraphNode_UseCachedPose_10;                    // 0x2930(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_44;                 // 0x2958(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_43;                 // 0x2980(0x28)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_17;                   // 0x29A8(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_28;                      // 0x29F0(0x20)()
	struct FAnimNode_RefPose                     AnimGraphNode_IdentityPose;                        // 0x2A10(0x10)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_27;                      // 0x2A20(0x20)()
	struct FAnimNode_StateMachine                AnimGraphNode_StateMachine_9;                      // 0x2A40(0xC8)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive_12;                    // 0x2B08(0xC8)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_26;                      // 0x2BD0(0x20)()
	struct FAnimNode_StateMachine                AnimGraphNode_StateMachine_8;                      // 0x2BF0(0xC8)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_25;                      // 0x2CB8(0x20)()
	struct FAnimNode_UseCachedPose               AnimGraphNode_UseCachedPose_9;                     // 0x2CD8(0x28)()
	struct FAnimNode_ModifyCurve                 AnimGraphNode_ModifyCurve_1;                       // 0x2D00(0x100)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_24;                      // 0x2E00(0x20)()
	struct FAnimNode_StateMachine                AnimGraphNode_StateMachine_7;                      // 0x2E20(0xC8)()
	struct FAnimNode_SaveCachedPose              AnimGraphNode_SaveCachedPose_3;                    // 0x2EE8(0x100)()
	struct FAnimNode_BlendSpacePlayer            AnimGraphNode_BlendSpacePlayer_6;                  // 0x2FE8(0x70)()
	struct FAnimNode_SaveCachedPose              AnimGraphNode_SaveCachedPose_2;                    // 0x3058(0x100)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_42;                 // 0x3158(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_41;                 // 0x3180(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_40;                 // 0x31A8(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_39;                 // 0x31D0(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_38;                 // 0x31F8(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_37;                 // 0x3220(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_36;                 // 0x3248(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_35;                 // 0x3270(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_34;                 // 0x3298(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_33;                 // 0x32C0(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_32;                 // 0x32E8(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_31;                 // 0x3310(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_30;                 // 0x3338(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_29;                 // 0x3360(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_28;                 // 0x3388(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_27;                 // 0x33B0(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_26;                 // 0x33D8(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_25;                 // 0x3400(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_24;                 // 0x3428(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_23;                 // 0x3450(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_22;                 // 0x3478(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_21;                 // 0x34A0(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_20;                 // 0x34C8(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_19;                 // 0x34F0(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_18;                 // 0x3518(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_17;                 // 0x3540(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_16;                 // 0x3568(0x28)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_16;                   // 0x3590(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_23;                      // 0x35D8(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_15;                   // 0x35F8(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_22;                      // 0x3640(0x20)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_15;                 // 0x3660(0x28)()
	struct FAnimNode_StateMachine                AnimGraphNode_StateMachine_6;                      // 0x3688(0xC8)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_21;                      // 0x3750(0x20)()
	struct FAnimNode_UseCachedPose               AnimGraphNode_UseCachedPose_8;                     // 0x3770(0x28)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive_11;                    // 0x3798(0xC8)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_14;                   // 0x3860(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_20;                      // 0x38A8(0x20)()
	struct FAnimNode_UseCachedPose               AnimGraphNode_UseCachedPose_7;                     // 0x38C8(0x28)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive_10;                    // 0x38F0(0xC8)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_13;                   // 0x39B8(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_19;                      // 0x3A00(0x20)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive_9;                     // 0x3A20(0xC8)()
	struct FAnimNode_UseCachedPose               AnimGraphNode_UseCachedPose_6;                     // 0x3AE8(0x28)()
	struct FAnimNode_BlendSpacePlayer            AnimGraphNode_BlendSpacePlayer_5;                  // 0x3B10(0x70)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive_8;                     // 0x3B80(0xC8)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_14;                 // 0x3C48(0x28)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_12;                   // 0x3C70(0x48)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive_7;                     // 0x3CB8(0xC8)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_11;                   // 0x3D80(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_18;                      // 0x3DC8(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_10;                   // 0x3DE8(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_17;                      // 0x3E30(0x20)()
	struct FAnimNode_StateMachine                AnimGraphNode_StateMachine_5;                      // 0x3E50(0xC8)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_16;                      // 0x3F18(0x20)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_13;                 // 0x3F38(0x28)()
	struct FAnimNode_UseCachedPose               AnimGraphNode_UseCachedPose_5;                     // 0x3F60(0x28)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive_6;                     // 0x3F88(0xC8)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_12;                 // 0x4050(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_11;                 // 0x4078(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_10;                 // 0x40A0(0x28)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_9;                    // 0x40C8(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_15;                      // 0x4110(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_8;                    // 0x4130(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_14;                      // 0x4178(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_7;                    // 0x4198(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_13;                      // 0x41E0(0x20)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_9;                  // 0x4200(0x28)()
	struct FAnimNode_StateMachine                AnimGraphNode_StateMachine_4;                      // 0x4228(0xC8)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_12;                      // 0x42F0(0x20)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_8;                  // 0x4310(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_7;                  // 0x4338(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_6;                  // 0x4360(0x28)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_6;                    // 0x4388(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_11;                      // 0x43D0(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_5;                    // 0x43F0(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_10;                      // 0x4438(0x20)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_5;                  // 0x4458(0x28)()
	struct FAnimNode_StateMachine                AnimGraphNode_StateMachine_3;                      // 0x4480(0xC8)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_9;                       // 0x4548(0x20)()
	struct FAnimNode_UseCachedPose               AnimGraphNode_UseCachedPose_4;                     // 0x4568(0x28)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive_5;                     // 0x4590(0xC8)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_4;                  // 0x4658(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_3;                  // 0x4680(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_2;                  // 0x46A8(0x28)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult_1;                  // 0x46D0(0x28)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_4;                    // 0x46F8(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_8;                       // 0x4740(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_3;                    // 0x4760(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_7;                       // 0x47A8(0x20)()
	struct FAnimNode_StateMachine                AnimGraphNode_StateMachine_2;                      // 0x47C8(0xC8)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_6;                       // 0x4890(0x20)()
	struct FAnimNode_UseCachedPose               AnimGraphNode_UseCachedPose_3;                     // 0x48B0(0x28)()
	struct FAnimNode_LinkedAnimLayer             AnimGraphNode_LinkedAnimLayer;                     // 0x48D8(0xC8)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_5;                       // 0x49A0(0x20)()
	struct FAnimNode_UseCachedPose               AnimGraphNode_UseCachedPose_2;                     // 0x49C0(0x28)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive_4;                     // 0x49E8(0xC8)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_2;                    // 0x4AB0(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_4;                       // 0x4AF8(0x20)()
	struct FAnimNode_UseCachedPose               AnimGraphNode_UseCachedPose_1;                     // 0x4B18(0x28)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive_3;                     // 0x4B40(0xC8)()
	struct FAnimNode_TransitionResult            AnimGraphNode_TransitionResult;                    // 0x4C08(0x28)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer_1;                    // 0x4C30(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_3;                       // 0x4C78(0x20)()
	struct FAnimNode_SequencePlayer              AnimGraphNode_SequencePlayer;                      // 0x4C98(0x48)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_2;                       // 0x4CE0(0x20)()
	struct FAnimNode_StateMachine                AnimGraphNode_StateMachine_1;                      // 0x4D00(0xC8)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult_1;                       // 0x4DC8(0x20)()
	struct FAnimNode_UseCachedPose               AnimGraphNode_UseCachedPose;                       // 0x4DE8(0x28)()
	struct FAnimNode_StateResult                 AnimGraphNode_StateResult;                         // 0x4E10(0x20)()
	struct FAnimNode_StateMachine                AnimGraphNode_StateMachine;                        // 0x4E30(0xC8)()
	struct FAnimNode_SaveCachedPose              AnimGraphNode_SaveCachedPose_1;                    // 0x4EF8(0x100)()
	struct FAnimNode_BlendSpacePlayer            AnimGraphNode_BlendSpacePlayer_4;                  // 0x4FF8(0x70)()
	struct FAnimNode_SaveCachedPose              AnimGraphNode_SaveCachedPose;                      // 0x5068(0x100)()
	struct FFortAnimNode_GrindRailSlopeWarping   FortAnimGraphNode_GrindRailSlopeWarping;           // 0x5168(0x340)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace_1;             // 0x54A8(0x20)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace_1;             // 0x54C8(0x20)()
	struct FAnimNode_ModifyCurve                 AnimGraphNode_ModifyCurve;                         // 0x54E8(0x100)()
	struct FAnimNode_BlendSpacePlayer            AnimGraphNode_BlendSpacePlayer_3;                  // 0x55E8(0x70)()
	struct FAnimNode_Root                        AnimGraphNode_Root_3;                              // 0x5658(0x20)()
	struct FAnimNode_LinkedInputPose             AnimGraphNode_LinkedInputPose_3;                   // 0x5678(0xC0)()
	struct FAnimNode_LegIK                       AnimGraphNode_LegIK;                               // 0x5738(0xF8)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x5830(0x20)()
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x5850(0x20)()
	struct FAnimNode_Root                        AnimGraphNode_Root_2;                              // 0x5870(0x20)()
	struct FAnimNode_LinkedInputPose             AnimGraphNode_LinkedInputPose_2;                   // 0x5890(0xC0)()
	struct FAnimNode_LinkedInputPose             AnimGraphNode_LinkedInputPose_1;                   // 0x5950(0xC0)()
	struct FAnimNode_Root                        AnimGraphNode_Root_1;                              // 0x5A10(0x20)()
	struct FAnimNode_LinkedInputPose             AnimGraphNode_LinkedInputPose;                     // 0x5A30(0xC0)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive_2;                     // 0x5AF0(0xC8)()
	struct FAnimNode_BlendSpacePlayer            AnimGraphNode_BlendSpacePlayer_2;                  // 0x5BB8(0x70)()
	struct FAnimNode_BlendSpacePlayer            AnimGraphNode_BlendSpacePlayer_1;                  // 0x5C28(0x70)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive_1;                     // 0x5C98(0xC8)()
	struct FAnimNode_ApplyAdditive               AnimGraphNode_ApplyAdditive;                       // 0x5D60(0xC8)()
	struct FAnimNode_RotationOffsetBlendSpace    AnimGraphNode_RotationOffsetBlendSpace_1;          // 0x5E28(0x118)()
	struct FAnimNode_RotationOffsetBlendSpace    AnimGraphNode_RotationOffsetBlendSpace;            // 0x5F40(0x118)()
	struct FAnimNode_BlendSpacePlayer            AnimGraphNode_BlendSpacePlayer;                    // 0x6058(0x70)()
	struct FAnimNode_Root                        AnimGraphNode_Root;                                // 0x60C8(0x20)()

	static class UClass* StaticClass()
	{
		static class UClass* Clss = UObject::FindClassFast("GrindRail_Player_LayerAnimBP_C");
		return Clss;
	}

	void MovementMode_LowerBodyOverride(const struct FPoseLink& InLowerBodyPose, const struct FPoseLink& InSourcePose, struct FPoseLink* MovementMode_LowerBodyOverride);
	void MovementMode_LocomotionAdditives(const struct FPoseLink& InLocomotionAdditivesPose, struct FPoseLink* MovementMode_LocomotionAdditives);
	void MovementMode_SourcePose(const struct FPoseLink& InSourcePoseBase, struct FPoseLink* MovementMode_SourcePose);
	void MovementMode_FullBodyOverride(const struct FPoseLink& InputPoseFullBody, struct FPoseLink* MovementMode_FullBodyOverride);
	void MovementMode_FinalPoseOverride(const struct FPoseLink& InFinalPose, struct FPoseLink* MovementMode_FinalPoseOverride);
	void MovementMode_AimOffset(const struct FPoseLink& InAimOffsetsPose, const struct FPoseLink& InSourcePosePreAimOffsets, struct FPoseLink* MovementMode_AimOffset);
	void LocomotionAdditiveGroup(const struct FPoseLink& InPoseLocomotionAdditive, struct FPoseLink* LocomotionAdditiveGroup);
	void AnimGraph(struct FPoseLink* AnimGraph);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_GrindRail_Player_LayerAnimBP_AnimGraphNode_TransitionResult_1A4025C94AC4E34FBC9B23AB49CFD72E();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_GrindRail_Player_LayerAnimBP_AnimGraphNode_TransitionResult_CFB7F39F4D881298D08C1D96AD6AA6FA();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_GrindRail_Player_LayerAnimBP_AnimGraphNode_TransitionResult_FD09E8AA456E65281CC87F8A6C4113AC();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_GrindRail_Player_LayerAnimBP_AnimGraphNode_TransitionResult_DF95C1FE4A2F5813CB01DE80C013E1C6();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_GrindRail_Player_LayerAnimBP_AnimGraphNode_TransitionResult_5697EE674F17ADBB80BF75A833AFA309();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_GrindRail_Player_LayerAnimBP_AnimGraphNode_TransitionResult_3BE669A04B6B559EC4783B8E897AD836();
	void ExecuteUbergraph_GrindRail_Player_LayerAnimBP(int32 EntryPoint, bool CallFunc_BooleanOR_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue, bool CallFunc_Not_PreBool_ReturnValue_1, bool CallFunc_Not_PreBool_ReturnValue_2, bool CallFunc_BooleanAND_ReturnValue, bool CallFunc_BooleanAND_ReturnValue_1, bool CallFunc_Not_PreBool_ReturnValue_3, bool CallFunc_BooleanAND_ReturnValue_2, bool CallFunc_Not_PreBool_ReturnValue_4, bool CallFunc_BooleanOR_ReturnValue_1, bool CallFunc_BooleanOR_ReturnValue_2);
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
